export type ProductSeed = {
  slug: string;
  name: string;
  category: string;
  categorySlug: string;
  tagline: string;
  image: string;
  description: string;
  features: string[];
  startingPrice: number;
  sizes?: string[];
  colors: string[];
  printTypes: string[];
  printLocations?: string[];
};

export const PRODUCTS_SEED: ProductSeed[] = [
  {
    slug: "panther-tee",
    name: "Midnight Panther Tee",
    category: "Round T-Shirt",
    categorySlug: "round-tshirt",
    tagline: "Bold back-print panther, framed in deep florals.",
    image: "/images/products/panther-tee.png",
    description:
      "An oversized-fit tee with a striking black panther back print, surrounded by dark floral detailing — a statement piece for anyone who likes their prints bold.",
    features: ["100% combed cotton, 220 GSM", "Oversized unisex fit", "Large all-over back print"],
    startingPrice: 699,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black"],
    printTypes: ["Digital Print"],
    printLocations: ["Back"],
  },
  {
    slug: "doberman-tee",
    name: "Red-Eye Doberman Tee",
    category: "Round T-Shirt",
    categorySlug: "round-tshirt",
    tagline: "A striking Doberman portrait with a diamond collar.",
    image: "/images/products/doberman-tee.png",
    description:
      "A moody, large-format Doberman back print with glowing red eyes and a diamond-studded collar — available across black, red, and maroon bases.",
    features: ["100% combed cotton, 220 GSM", "Oversized unisex fit", "Large all-over back print"],
    startingPrice: 699,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Red", "Maroon"],
    printTypes: ["Digital Print"],
    printLocations: ["Back"],
  },
  {
    slug: "doberman-cigar-tee",
    name: "Doberman Pocket Tee",
    category: "Round T-Shirt",
    categorySlug: "round-tshirt",
    tagline: "A compact Doberman portrait, front pocket print.",
    image: "/images/products/doberman-cigar-tee.png",
    description:
      "The same sharp Doberman illustration in a smaller front pocket placement — a subtler everyday tee with a bit of edge.",
    features: ["100% combed cotton, 200 GSM", "Relaxed unisex fit", "Compact front print"],
    startingPrice: 599,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black"],
    printTypes: ["Digital Print"],
    printLocations: ["Front"],
  },
  {
    slug: "king-lion-tee",
    name: "King of Hearts Tee",
    category: "Round T-Shirt",
    categorySlug: "round-tshirt",
    tagline: "A regal lion, illustrated as the King of Hearts.",
    image: "/images/products/king-lion-tee.png",
    description:
      "A playing-card-inspired lion portrait printed front and back on a clean white tee — sharp enough for a night out, simple enough for every day.",
    features: ["100% combed cotton, 200 GSM", "Relaxed unisex fit", "Front & back print"],
    startingPrice: 599,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White"],
    printTypes: ["Digital Print"],
    printLocations: ["Front & Back"],
  },
  {
    slug: "black-horse-tee",
    name: "Black Horse Pocket Tee",
    category: "Round T-Shirt",
    categorySlug: "round-tshirt",
    tagline: "A fine-art horse portrait, front pocket print.",
    image: "/images/products/black-horse-tee.png",
    description:
      "A charcoal-style horse portrait on a dramatic red backdrop, printed small and clean on the front — understated but distinctive.",
    features: ["100% combed cotton, 200 GSM", "Relaxed unisex fit", "Compact front print"],
    startingPrice: 599,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black"],
    printTypes: ["Digital Print"],
    printLocations: ["Front"],
  },
  {
    slug: "white-tiger-tee",
    name: "Porcelain Tiger Tee",
    category: "Round T-Shirt",
    categorySlug: "round-tshirt",
    tagline: "A roaring tiger in porcelain-floral patternwork.",
    image: "/images/products/white-tiger-tee.png",
    description:
      "An artistic, oversized tiger print styled like hand-painted porcelain, finished with a jewelled collar — a true conversation-starter tee.",
    features: ["100% combed cotton, 220 GSM", "Oversized unisex fit", "Large wraparound print"],
    startingPrice: 699,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White"],
    printTypes: ["Digital Print"],
    printLocations: ["Front"],
  },
  {
    slug: "statue-tee",
    name: "Classic Sipper Tee",
    category: "Round T-Shirt",
    categorySlug: "round-tshirt",
    tagline: "A classical bust, reimagined with shades and a cold drink.",
    image: "/images/products/statue-tee.png",
    description:
      "A witty mashup of classical sculpture and modern-day chill — a marble bust in sunglasses, sipping an iced drink. Playful and easy to wear.",
    features: ["100% combed cotton, 200 GSM", "Relaxed unisex fit", "Front print"],
    startingPrice: 599,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White"],
    printTypes: ["Digital Print"],
    printLocations: ["Front"],
  },
  {
    slug: "old-money-tee",
    name: "Old Money Tee",
    category: "Round T-Shirt",
    categorySlug: "round-tshirt",
    tagline: "A vintage-crest polo-match illustration.",
    image: "/images/products/old-money-tee.png",
    description:
      "A vintage crest-style print inspired by classic equestrian sport — clean typography and fine linework for an understated, premium look.",
    features: ["100% combed cotton, 200 GSM", "Relaxed unisex fit", "Front print"],
    startingPrice: 599,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White"],
    printTypes: ["Digital Print"],
    printLocations: ["Front"],
  },
  {
    slug: "blah-blah-tee",
    name: "Blah Blah Blah Tee",
    category: "Round T-Shirt",
    categorySlug: "round-tshirt",
    tagline: "Bold pop-art type with a vintage collage edge.",
    image: "/images/products/blah-blah-tee.png",
    description:
      "A graphic, collage-style print with bold lettering and a retro, torn-paper look — for when your tee needs to do the talking.",
    features: ["100% combed cotton, 200 GSM", "Relaxed unisex fit", "Front print"],
    startingPrice: 599,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black"],
    printTypes: ["Digital Print"],
    printLocations: ["Front"],
  },
  {
    slug: "goose-tee",
    name: "Cool Goose Tee",
    category: "Round T-Shirt",
    categorySlug: "round-tshirt",
    tagline: "A sunglasses-and-headscarf goose, dressed to impress.",
    image: "/images/products/goose-tee.png",
    description:
      "A playful illustrated goose in oversized sunglasses and a headscarf — lighthearted, quirky, and easy to pair with anything.",
    features: ["100% combed cotton, 200 GSM", "Relaxed unisex fit", "Front print"],
    startingPrice: 599,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black"],
    printTypes: ["Digital Print"],
    printLocations: ["Front"],
  },
  {
    slug: "hot-mess-tee",
    name: "Hot Mess Tee",
    category: "Round T-Shirt",
    categorySlug: "round-tshirt",
    tagline: "A retro flame script, equal parts sweet and sassy.",
    image: "/images/products/hot-mess-tee.png",
    description:
      "A retro hot-rod-style script wordmark in soft rose tones — fun, a little cheeky, and effortless to style.",
    features: ["100% combed cotton, 200 GSM", "Relaxed unisex fit", "Front print"],
    startingPrice: 599,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White"],
    printTypes: ["Digital Print"],
    printLocations: ["Front"],
  },
  {
    slug: "masala-life-tee",
    name: "Masala Life Tee",
    category: "Round T-Shirt",
    categorySlug: "round-tshirt",
    tagline: "Add some masala to your life.",
    image: "/images/products/tshirt.png",
    description:
      "A colourful, Hindi-English mashup typographic print with retro spice-tin energy — bright, bold, and full of flavour.",
    features: ["100% combed cotton, 200 GSM", "Relaxed unisex fit", "Front print"],
    startingPrice: 599,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White"],
    printTypes: ["Digital Print"],
    printLocations: ["Front"],
  },
  {
    slug: "serial-chiller-tee",
    name: "Serial Chiller Tee",
    category: "Round T-Shirt",
    categorySlug: "round-tshirt",
    tagline: "A sunglasses-clad icon, dialled all the way to chill.",
    image: "/images/products/serial-chiller-tee.png",
    description:
      "A playful illustrated character in oversized shades with the words 'Serial Chiller' — easygoing, fun, and instantly recognizable.",
    features: ["100% combed cotton, 200 GSM", "Relaxed unisex fit", "Front print"],
    startingPrice: 599,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White"],
    printTypes: ["Digital Print"],
    printLocations: ["Front"],
  },
  {
    slug: "better-late-ugly-tee",
    name: "Better Late Than Ugly Tee",
    category: "Round T-Shirt",
    categorySlug: "round-tshirt",
    tagline: "A pampered cat, dressed for the occasion.",
    image: "/images/products/better-late-ugly-tee.png",
    description:
      "A cheeky illustrated cat in a towel turban and shades, with a line that says it all — a feel-good pick for cat lovers.",
    features: ["100% combed cotton, 200 GSM", "Relaxed unisex fit", "Front print"],
    startingPrice: 599,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White"],
    printTypes: ["Digital Print"],
    printLocations: ["Front"],
  },
  {
    slug: "kaam-se-kaam-tee",
    name: "Keep Kaam Se Kaam Tee",
    category: "Round T-Shirt",
    categorySlug: "round-tshirt",
    tagline: "A floral, illustrated nod to minding your own business.",
    image: "/images/products/kaam-se-kaam-tee.png",
    description:
      "A rich floral illustration framing a Hindi-English wordplay print — detailed, artistic, and full of personality.",
    features: ["100% combed cotton, 200 GSM", "Relaxed unisex fit", "Front print"],
    startingPrice: 599,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White"],
    printTypes: ["Digital Print"],
    printLocations: ["Front"],
  },
  {
    slug: "vitamin-p-tee",
    name: "Vitamin P Tee",
    category: "Round T-Shirt",
    categorySlug: "round-tshirt",
    tagline: "A frothy mug illustration with a cheeky Hindi pun.",
    image: "/images/products/vitamin-p-tee.png",
    description:
      "A hand-drawn beer mug print with a playful Hindi wordplay — easygoing, fun, and great for weekend wear.",
    features: ["100% combed cotton, 200 GSM", "Relaxed unisex fit", "Front print"],
    startingPrice: 599,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black"],
    printTypes: ["Digital Print"],
    printLocations: ["Front"],
  },
  {
    slug: "rich-risk-tee",
    name: "Rich Risk Tee",
    category: "Round T-Shirt",
    categorySlug: "round-tshirt",
    tagline: "Playful tile-letter wordplay on bold red.",
    image: "/images/products/rich-risk-tee.png",
    description:
      "A clever Boggle-tile-style print that reads 'RICH' or 'RISK' depending how you look at it — simple, graphic, and sharp.",
    features: ["100% combed cotton, 200 GSM", "Relaxed unisex fit", "Front print"],
    startingPrice: 599,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Red"],
    printTypes: ["Digital Print"],
    printLocations: ["Front"],
  },
  {
    slug: "weirdo-tee",
    name: "Weirdo Tee",
    category: "Round T-Shirt",
    categorySlug: "round-tshirt",
    tagline: "A taped-on label, worn with pride.",
    image: "/images/products/weirdo-tee.png",
    description:
      "A simple, sticker-style 'Weirdo' print on a clean black tee — minimal, confident, and easy to wear.",
    features: ["100% combed cotton, 200 GSM", "Relaxed unisex fit", "Front print"],
    startingPrice: 599,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black"],
    printTypes: ["Digital Print"],
    printLocations: ["Front"],
  },
  {
    slug: "do-not-disturb-tee",
    name: "Do Not Disturb Tee",
    category: "Round T-Shirt",
    categorySlug: "round-tshirt",
    tagline: "Bold retro type for an honest mood.",
    image: "/images/products/do-not-disturb-tee.png",
    description:
      "A bold, retro-groove typographic print that says exactly what it means — a fun pick for low-key days.",
    features: ["100% combed cotton, 200 GSM", "Relaxed unisex fit", "Front print"],
    startingPrice: 599,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black"],
    printTypes: ["Digital Print"],
    printLocations: ["Front"],
  },
  {
    slug: "measure-value-tee",
    name: "Measure Your Value Tee",
    category: "Round T-Shirt",
    categorySlug: "round-tshirt",
    tagline: "A gentle reminder, illustrated with measuring tape.",
    image: "/images/products/measure-value-tee.jpg",
    description:
      "A soft, pastel illustration with an encouraging message — a thoughtful, feel-good tee for everyday wear or gifting.",
    features: ["100% combed cotton, 200 GSM", "Relaxed unisex fit", "Front print"],
    startingPrice: 599,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White"],
    printTypes: ["Digital Print"],
    printLocations: ["Front"],
  },
  {
    slug: "beparwah-tee",
    name: "Beparwah Tee",
    category: "Round T-Shirt",
    categorySlug: "round-tshirt",
    tagline: "A dreamy floral collage with a carefree Hindi title.",
    image: "/images/products/beparwah-tee.jpg",
    description:
      "An artistic collage print layering florals and vintage portraiture — moody, aesthetic, and a little nostalgic.",
    features: ["100% combed cotton, 200 GSM", "Relaxed unisex fit", "Front print"],
    startingPrice: 599,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White"],
    printTypes: ["Digital Print"],
    printLocations: ["Front"],
  },
  {
    slug: "polo-tee",
    name: "Show Me The Money Polo",
    category: "Polo T-Shirt",
    categorySlug: "polo-tshirt",
    tagline: "Bold graphic polo with a playful money print.",
    image: "/images/products/polo-tshirt.png",
    description:
      "A smart-casual polo with a bold graphic front print — collared, comfortable, and ready to make a statement.",
    features: ["100% cotton pique, 220 GSM", "Ribbed collar & cuffs", "Unisex fit"],
    startingPrice: 599,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Red"],
    printTypes: ["Digital Print"],
    printLocations: ["Front"],
  },
  {
    slug: "shirt",
    name: "Button-Up Shirt",
    category: "Shirt",
    categorySlug: "shirt",
    tagline: "Collared everyday shirt, printed or embroidered.",
    image: "/images/category-shirt.jpg",
    description:
      "A clean, collared button-up for a smarter everyday look — printed or embroidered with your design, ideal for uniforms and formal gifting.",
    features: ["100% cotton poplin", "Classic collar & button placket", "Regular unisex fit"],
    startingPrice: 799,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Light Blue"],
    printTypes: ["Embroidery", "Digital Print"],
    printLocations: ["Front", "Sleeve"],
  },
  {
    slug: "hoodie",
    name: "Hoodie",
    category: "Hoodie",
    categorySlug: "hoodie",
    tagline: "Cozy fleece hoodie, made for your design.",
    image: "/images/category-hoodie.jpg",
    description:
      "A heavyweight fleece hoodie with a relaxed unisex fit — perfect for cooler days, streetwear drops, and team merch.",
    features: ["280 GSM cotton-fleece blend", "Kangaroo pocket", "Adjustable drawstring hood"],
    startingPrice: 899,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Black", "Grey Melange"],
    printTypes: ["Digital Print", "Embroidery"],
    printLocations: ["Front", "Back"],
  },
  {
    slug: "tote-bag",
    name: "Karma Is A Cat Tote",
    category: "Bag",
    categorySlug: "bag",
    tagline: "A playful canvas tote with a cheeky cat illustration.",
    image: "/images/products/bag-tote.jpg",
    description:
      "A sturdy canvas tote printed with a cheeky illustrated cat and a line that says it all — great for everyday carry or as a light, fun gift.",
    features: ["Heavy-duty cotton canvas", "Reinforced handles", "One size"],
    startingPrice: 299,
    colors: ["Natural"],
    printTypes: ["Digital Print"],
    printLocations: ["Front"],
  },
  {
    slug: "mug",
    name: "Printed Mug",
    category: "Mug",
    categorySlug: "mug",
    tagline: "Ceramic mug, printed with your design.",
    image: "/images/category-mug.jpg",
    description:
      "A classic ceramic mug printed edge-to-edge with your design — a simple, affordable gift or merch add-on.",
    features: ["Ceramic, 325 ml", "Dishwasher & microwave safe", "Full-wrap print"],
    startingPrice: 249,
    colors: ["White"],
    printTypes: ["Digital Print (all-over)"],
    printLocations: ["Wraparound"],
  },
  {
    slug: "cap",
    name: "Cap",
    category: "Accessories",
    categorySlug: "accessories",
    tagline: "Adjustable cap with your logo or design.",
    image: "/images/category-cap.jpg",
    description:
      "An adjustable, structured cap — a popular add-on for uniforms, events, and corporate merch kits.",
    features: ["Cotton twill front panel", "Adjustable strap", "One size fits most"],
    startingPrice: 349,
    colors: ["White", "Black", "Navy"],
    printTypes: ["Embroidery", "Print & Cut"],
    printLocations: ["Front"],
  },
  {
    slug: "printed-pillow",
    name: "Printed Pillow",
    category: "Pillow",
    categorySlug: "pillow",
    tagline: "Turn your favourite design into home decor.",
    image: "/images/category-pillow.jpg",
    description:
      "A soft square cushion cover, printed edge-to-edge with your design — a lovely personalised gift or home accent.",
    features: ["Premium poly-linen cover", "Concealed zip closure", "16 x 16 inch"],
    startingPrice: 449,
    colors: ["As per design"],
    printTypes: ["Digital Print (all-over)"],
    printLocations: ["Front", "Front & Back"],
  },
  {
    slug: "custom-design",
    name: "Custom Design",
    category: "Custom",
    categorySlug: "custom",
    tagline: "Bring your own art — we'll print it on demand.",
    image: "/images/category-custom.jpg",
    description:
      "Not sure what to order? Send us your artwork, photo, or idea and we'll match it to the right product and print method.",
    features: ["Free design consultation", "Digital proof before printing", "Any product in our catalog"],
    startingPrice: 299,
    colors: ["Depends on product"],
    printTypes: ["Digital Print", "Print & Cut", "Embroidery"],
    printLocations: ["Front", "Back", "Front & Back"],
  },
];
